# Regression Models Explained with Python
**Dataset:** Retail customer spending

This notebook explains multiple regression models using the **same dataset** so it is easier to compare them.

Models covered:
- Linear Regression
- Logistic Regression (classification example)
- Polynomial Regression
- Ridge Regression
- Lasso Regression
- ElasticNet Regression
- Decision Tree Regression
- Random Forest Regression
- Support Vector Regression (SVR)

Generated on 2026-03-07

## Regression

#### Regression is a supervised machine learning technique used to predict a continuous numerical value based on input features.

## Common Types of Regression Analysis

- **Linear Regression:** Fits a straight line to establish relationships between a continuous dependent variable and one or more independent variables.
- **Logistic Regression:** Used when the dependent variable is discrete (binary/classification) rather than continuous.
- **Polynomial Regression:** Models nonlinear relationships by using higher-order terms for the independent variable.
- **Ridge Regression (L2 Regularization):** A technique used to reduce overfitting in linear models by shrinking coefficients, particularly useful when independent variables are highly correlated.
- **Lasso Regression (L1 Regularization):** Similar to ridge, but shrinks some coefficients to zero, allowing for automated feature selection.
- **ElasticNet Regression:** Combines both Ridge and Lasso regression methods, useful when multiple independent variables are dominant.
- **Decision Tree/Random Forest Regression:** Non-parametric methods that split data into branches to predict a continuous outcome.
- **Support Vector Regression (SVR):** Handles linear and nonlinear data by finding a hyperplane that fits the data within a specified tolerance.
- **Other Types:**
    - Stepwise Regression: Selects independent variables automatically based on their significance.
    - Quantile Regression: Estimates the median or other quantiles of the dependent variable.
    - Poisson/Negative Binomial Regression: Used for modeling count data, with Negative Binomial handling overdispersion.

## Step 1: Import Libraries

In [2]:
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import PolynomialFeatures, StandardScaler

from sklearn.linear_model import (
    LinearRegression,
    LogisticRegression,
    Ridge,
    Lasso,
    ElasticNet
)

from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor
from sklearn.svm import SVR

## Step 2: Create Sample Retail Dataset

In [3]:
data = {
    'age': [25,32,47,51,62,23,36,44,28,55],
    'income': [40000,52000,78000,90000,110000,35000,65000,72000,48000,99000],
    'years_customer': [1,3,10,7,15,2,5,8,3,12],
    'is_subscribed': [1,0,1,1,1,0,0,1,0,1],
    'annual_spending': [2000,3200,7200,6800,9500,1800,4000,6200,3100,8800]
}

df = pd.DataFrame(data)
df

   age  income  years_customer  is_subscribed  annual_spending
0   25   40000               1              1             2000
1   32   52000               3              0             3200
2   47   78000              10              1             7200
3   51   90000               7              1             6800
4   62  110000              15              1             9500
5   23   35000               2              0             1800
6   36   65000               5              0             4000
7   44   72000               8              1             6200
8   28   48000               3              0             3100
9   55   99000              12              1             8800

## Step 3: Split Dataset

In [4]:
X = df.drop('annual_spending', axis=1)
y = df['annual_spending']

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

In [7]:
X_train

   age  income  years_customer  is_subscribed
5   23   35000               2              0
0   25   40000               1              1
7   44   72000               8              1
2   47   78000              10              1
9   55   99000              12              1
4   62  110000              15              1
3   51   90000               7              1
6   36   65000               5              0

In [6]:
X_test

   age  income  years_customer  is_subscribed
8   28   48000               3              0
1   32   52000               3              0

## 1. Linear Regression
Fits a straight line relationship between features and target.

Pros

✔ Easy to understand

✔ Very fast

✔ Works well when relationship is linear

Cons

❌ Cannot capture complex patterns

❌ Sensitive to outliers

❌ Poor performance for nonlinear data

In [8]:
model = LinearRegression()
model.fit(X_train, y_train)

predictions = model.predict(X_test)
print(predictions)

[2589.71074923 3138.01856   ]

## 2. Logistic Regression
Used for classification problems. Here we convert spending into a binary class.

Pros

✔ Simple and interpretable

✔ Works well for binary classification

✔ Probabilistic output

Cons

❌ Cannot model complex relationships

❌ Assumes linear decision boundary

In [14]:
# Convert spending to high spender vs low spender.
y_class = (y > 5000).astype(int)

print(X)        # features:["age","income","years_customer","is_subscribed"]
print(y_class)  # target: 1 for high spender, 0 for low spender

X_train_c, X_test_c, y_train_c, y_test_c = train_test_split(
    X, y_class, test_size=0.2, random_state=42
)

model = LogisticRegression()
model.fit(X_train_c, y_train_c)

predictions = model.predict(X_test_c)
print(X_test_c)
predictions

   age  income  years_customer  is_subscribed
0   25   40000               1              1
1   32   52000               3              0
2   47   78000              10              1
3   51   90000               7              1
4   62  110000              15              1
5   23   35000               2              0
6   36   65000               5              0
7   44   72000               8              1
8   28   48000               3              0
9   55   99000              12              1
0    0
1    0
2    1
3    1
4    1
5    0
6    0
7    1
8    0
9    1
Name: annual_spending, dtype: int64
   age  income  years_customer  is_subscribed
8   28   48000               3              0
1   32   52000               3              0

d:\code\ML-Learnings\machine-learning\.venv\lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

array([0, 0])

## 3. Polynomial Regression
Captures nonlinear relationships.

Pros

✔ Captures nonlinear patterns

✔ Still interpretable

Cons

❌ Can overfit easily

❌ Number of features increases quickly

In [15]:
poly = PolynomialFeatures(degree=2)

X_train_poly = poly.fit_transform(X_train)
X_test_poly = poly.transform(X_test)

model = LinearRegression()
model.fit(X_train_poly, y_train)

predictions = model.predict(X_test_poly)
predictions

array([2709.9297113 , 2006.02102394])

## 4. Ridge Regression (L2 Regularization)
Helps reduce overfitting by shrinking coefficients.

When features are highly correlated, coefficients become unstable.

Pros

✔ Reduces overfitting

✔ Handles multicollinearity well

Cons

❌ Does not eliminate features

❌ Harder to interpret coefficients

In [16]:
model = Ridge(alpha=1.0)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions

array([2650.32291833, 3301.9171527 ])

## 5. Lasso Regression (L1 Regularization)
Performs feature selection by shrinking some coefficients to zero.

Pros

✔ Feature selection

✔ Reduces overfitting

Cons

❌ Can remove useful features if alpha too high

❌ Unstable with highly correlated features

In [17]:
model = Lasso(alpha=0.1)
model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions

d:\code\ML-Learnings\machine-learning\.venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.282e+05, tolerance: 5.949e+03
  model = cd_fast.enet_coordinate_descent(

array([2590.04090018, 3138.74935391])

## 6. ElasticNet Regression
Combination of Ridge and Lasso regularization.

Useful when:

many features exist

correlated features exist

Pros

✔ Combines strengths of Ridge & Lasso

✔ Works well with many features

Cons

❌ Requires tuning two parameters

❌ Slightly more complex

In [18]:
model = ElasticNet(alpha=0.1, l1_ratio=0.5)

model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions

d:\code\ML-Learnings\machine-learning\.venv\lib\site-packages\sklearn\linear_model\_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.613e+05, tolerance: 5.949e+03
  model = cd_fast.enet_coordinate_descent(

array([2624.43837156, 3244.7122463 ])

## 7. Decision Tree Regression
Creates rule-based splits to predict the target.

Pros

✔ Handles nonlinear data

✔ Easy to visualize

✔ No scaling required

Cons

❌ Overfitting risk

❌ Unstable (small changes affect tree)

In [19]:
model = DecisionTreeRegressor(max_depth=3)

model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions

array([2000., 2000.])

## 8. Random Forest Regression
Uses multiple trees and averages predictions.

Pros

✔ High accuracy

✔ Handles complex relationships

✔ Reduces overfitting

Cons

❌ Less interpretable

❌ Slower training

In [20]:
model = RandomForestRegressor(n_estimators=100, random_state=42)

model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions

array([2132., 2582.])

## 9. Support Vector Regression (SVR)
Works well for complex nonlinear relationships.

Pros

✔ Handles nonlinear data well

✔ Works in high dimensional spaces

Cons

❌ Slow for large datasets

❌ Requires careful parameter tuning

In [21]:
scaler = StandardScaler()

X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

model = SVR(kernel='rbf')

model.fit(X_train_scaled, y_train)

predictions = model.predict(X_test_scaled)
predictions

array([6496.73885317, 6496.79354191])

| Model                 | Best For                 | Complexity |
| --------------------- | ------------------------ | ---------- |
| Linear Regression     | Simple relationships     | Low        |
| Logistic Regression   | Binary classification    | Low        |
| Polynomial Regression | Curved relationships     | Medium     |
| Ridge                 | Multicollinearity        | Medium     |
| Lasso                 | Feature selection        | Medium     |
| ElasticNet            | Many correlated features | Medium     |
| Decision Tree         | Nonlinear patterns       | Medium     |
| Random Forest         | High accuracy            | High       |
| SVR                   | Complex nonlinear data   | High       |

XGBoost does not belong to a single regression model type like Linear or Polynomial regression.
Instead, it belongs to a broader family called Gradient Boosting models.

Tree-based Gradient Boosting Regression model

## How XGBoost Works (Simple Idea)

Instead of training one model, XGBoost trains many small decision trees **sequentially**.  
Each new tree tries to correct the errors made by the previous trees.

**Example workflow:**

In [24]:
import pandas as pd
from xgboost import XGBRegressor
from sklearn.model_selection import train_test_split

data = {
    'age': [25,32,47,51,62,23,36,44,28,55],
    'income': [40000,52000,78000,90000,110000,35000,65000,72000,48000,99000],
    'years_customer': [1,3,10,7,15,2,5,8,3,12],
    'is_subscribed': [1,0,1,1,1,0,0,1,0,1],
    'annual_spending': [2000,3200,7200,6800,9500,1800,4000,6200,3100,8800]
}

df = pd.DataFrame(data)

X = df.drop("annual_spending", axis=1)
y = df["annual_spending"]

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

model = XGBRegressor()

model.fit(X_train, y_train)

predictions = model.predict(X_test)
predictions

array([2000.0001, 2000.0001], dtype=float32)

Bagging vs Boosting

Both Bagging and Boosting are ensemble learning techniques.

They combine multiple models to produce better predictions than a single model.

Bagging (Bootstrap Aggregating)

Bagging builds multiple models independently using different random samples of the dataset.

The final prediction is the average (regression) or majority vote (classification).

One popular bagging algorithm is Random Forest.
## Bagging (Bootstrap Aggregating)

Bagging builds multiple models independently using different random samples of the dataset.

The final prediction is the average (regression) or majority vote (classification).

One popular bagging algorithm is **Random Forest**.

### How Bagging Works

Step‑by‑step:

1. Original dataset  
2. Create multiple random samples (bootstrap)  
3. Train separate models on each sample  
4. Combine predictions (average or voting)

**Key characteristics**

- Models are trained independently  
- Reduces variance  
- Works well with high‑variance models like decision trees
How Bagging Works

Step-by-step:

Original Dataset

  ↓  
Create multiple random samples (bootstrap)

  ↓  
Train separate models on each sample

  ↓  
Combine predictions (average or voting)

Key Characteristics

- ✔ Models are trained independently
- ✔ Reduces variance
- ✔ Works well with high variance models like decision trees

## Boosting

Boosting trains models sequentially.  
Each new model focuses on correcting the errors of the previous model.

Popular boosting algorithms include:

- XGBoost
- LightGBM
- AdaBoost

**Key Characteristics**

- ✔ Models trained sequentially
- ✔ Focus on reducing bias
- ✔ Usually more accurate but slower

Bagging vs Boosting (Comparison)

| Feature          | Bagging   | Boosting    |
|------------------|-----------|-------------|
| Training         | Parallel  | Sequential  |
| Goal             | Reduce variance | Reduce bias |
| Model dependency | Independent | Dependent   |
| Speed            | Faster    | Slower      |
| Overfitting      | Lower     | Can overfit |

Dataset  
        ↓  
Random samples  
        ↓  
Tree 1  
Tree 2  
Tree 3  
Tree 4  
        ↓  
Average prediction

## XGBoost

XGBoost is a boosting algorithm that builds trees sequentially.  
Each new tree attempts to correct the errors of the previous trees.  
It is based on the concept of gradient boosting.

### Pros
- ✔ Very high prediction accuracy
- ✔ Handles missing values automatically
- ✔ Built‑in regularization
- ✔ Efficient with large datasets

### Cons
- ✖ More complex to tune
- ✖ Training slower than Random Forest
- ✖ Many hyperparameters

### XGBoost Workflow
1. Tree 1 → prediction  
2. Error calculation  
3. Tree 2 → corrects error  
4. Tree 3 → further improves  

Final prediction = sum of all trees

Random Forest vs XGBoost (Comparison)
Feature	Random Forest	XGBoost
Type	Bagging	Boosting
Tree Training	Parallel	Sequential
Speed	Faster training	Slower
Accuracy	Good	Usually better
Overfitting	Lower	Controlled with regularization
Hyperparameters	Few	Many

### Real Industry Rule of Thumb

Data scientists often follow this approach:

Start with **Random Forest**  
↓  
If performance not enough  
↓  
Try **XGBoost / LightGBM**